### ISSUE TITLE
Create Figma mockup for Newsfeed page

### ISSUE THREAD

**Issue by asdfghjk0416** [RyChrome/openbeats#14]
**Task Test(s)**

_Task Test 1_
1. Open up[ Figma Link](https://www.figma.com/file/4wg2mvCkOCg37OxxORFVqC/News-Feed?node-id=137%3A11116)
2. Verify that the Newsfeed UI has been completed

**Comment by asdfghjk0416** [comment]
[link](https://www.figma.com/file/4wg2mvCkOCg37OxxORFVqC/News-Feed?node-id=137%3A11116)

**Comment by ethan-richardson** [comment]
Needs task test format
