### ISSUE TITLE
Create Figma for "Your Profile Section"

### ISSUE THREAD

**Issue by RyChrome** [RyChrome/openbeats#24]
**Task Test(s)**

_Task Test 1_
1. Open up [ Figma Link](https://www.figma.com/file/4wg2mvCkOCg37OxxORFVqC/News-Feed?node-id=137%3A11116)
2. Verify that the Your Profile section UI has been completed

**Comment by bailey8** [comment]
@asdfghjk0416 we just made this page so there isn't a need for the figma mockup

**Comment by ethan-richardson** [comment]
Put this in task test format and add a link to the Figma
