### ISSUE TITLE
Add search bar to NavBar in Tailwind

### ISSUE THREAD

**Issue by RyChrome** [RyChrome/openbeats#25]
**Task Test(s)**

_Task Test 1_
1. Start the Open Beats application locally using `docker-compose up` in the root level directory 
2. Click Sign In
3. Sign in using the following credentials:
**email:** dilsy3@gmail.com
**password:** password
4. Verify there is a Search Bar in the navigation bar by looking for the input form field that says "Search". This should be located somewhere in the top of the page near the middle.
5. Type something in the search bar

**Comment by ethan-richardson** [comment]
Needs task test formatting
