### ISSUE TITLE
As a musical artist interested in purchasing an Open Beats subscription, I would like to see the pricing page so that I can see the price of each plan and weigh their pros and cons

### ISSUE THREAD

**Issue by RyChrome** [RyChrome/openbeats#42]
**Acceptance Test**

_Test 1:_
1. Navigate to "Pricing" in the Navigation Bar at the top of the page
2. Click "Pricing" in the Navigation Bar at the top of the page
3. Be successfully redirected to the pricing section
4. View an image that looks like this.

![Screen Shot 2021-10-04 at 6.03.34 PM.png](https://images.zenhubusercontent.com/5e3dcd061c8ae8c27d02bfb7/841fc0d2-544f-4694-999e-3fb54de45e5a)

**Comment by ethan-richardson** [comment]
Needs task test format
