### ISSUE TITLE
As a music artist who would like to learn more than what's on the landing page about Open Beats, I would like to click About to learn more about Open Beats

### ISSUE THREAD

**Issue by RyChrome** [RyChrome/openbeats#51]
**Acceptance Test**
_Test 1:_

1.) Start the Open Beats application locally by navigating to the root in the project directory in the `develop` branch and running `docker-compose up` and navigating to http://localhost
2.) Click "About" in the top left (next to the logo)
3.) Be redirected to a separate page that explains the goal of Open Beats

**Comment by ethan-richardson** [comment]
Link Open Beats homepage for step 1. Bold "Acceptance Tests" and add "Test 1" in italics
