### ISSUE TITLE
Remove es-lint warnings by fixing them

### ISSUE THREAD

**Issue by RyChrome** [RyChrome/openbeats#54]
Remove es-lint warnings that show up after running a `docker-compose up`. 

This is something that can be worked on throughout sprints when people get stuck on tasks and maybe want to work on something else.

You will know that the Task is complete when you run the `docker-compose up` command and get no errors.

**Comment by ethan-richardson** [comment]
You can remove all of the labels for this since it isn't related to a specific User Story and then I'll close it out.
